#!/usr/bin/env python3
"""
Generate docs/claims.md from the calibra/claims/*.json registry.

Run from the repo root:
    python scripts/generate_claims_doc.py
    python scripts/generate_claims_doc.py --out docs/claims.md
    python scripts/generate_claims_doc.py --check   # exit 1 if ratio is inverted

The generated file is committed to docs/claims.md so contributors and
researchers can read the knowledge base without needing to parse JSON.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

_REPO = Path(__file__).parent.parent
sys.path.insert(0, str(_REPO))

from calibra.claims import _derive_confidence  # noqa: E402  # reuse the same scale

_STATUS_EMOJI = {
    "validated":        "✅ validated",
    "active_hypothesis":"🔬 active hypothesis",
    "provisional":      "⚠️  provisional",
    "falsified":        "❌ falsified",
    "updated":          "🔄 updated",
    "superseded":       "🔁 superseded",
}

_CONFIDENCE_BADGE = {
    "STRONG":        "🟢 STRONG",
    "HIGH":          "🟢 HIGH",
    "MEDIUM":        "🟡 MEDIUM",
    "MODERATE":      "🟡 MODERATE",
    "LOW-MODERATE":  "🟠 LOW-MODERATE",
    "LOW":           "🟠 LOW",
    "NOT VALIDATED": "⬜ NOT VALIDATED",
}


def load_claims(claims_dir: Path) -> list[dict]:
    claims = []
    for path in sorted(claims_dir.glob("*.json")):
        try:
            data = json.loads(path.read_text())
        except json.JSONDecodeError as e:
            print(f"Warning: could not parse {path}: {e}", file=sys.stderr)
            continue
        for claim in data.get("claims", []):
            claim["_source_file"] = path.name
            claim["confidence"] = _derive_confidence(claim)
            claims.append(claim)
    return sorted(claims, key=lambda c: c.get("id", ""))


def load_references(refs_dir: Path) -> list[str]:
    return [p.stem for p in sorted(refs_dir.glob("*.json"))]


def render_claims_doc(claims: list[dict], references: list[str]) -> str:
    n_claims = len(claims)
    n_refs = len(references)
    ratio_ok = n_refs >= n_claims
    ratio_icon = "✅" if ratio_ok else "⚠️ "

    lines = [
        "# Calibra Claim Registry",
        "",
        "This file is auto-generated by `scripts/generate_claims_doc.py`.",
        "Do not edit manually — edit the source JSON files in `calibra/claims/`.",
        "",
        "---",
        "",
        "## Health",
        "",
        "| Stat | Value |",
        "|------|-------|",
        f"| Active claims | {n_claims} |",
        f"| Reference profiles | {n_refs} |",
        f"| Ratio | {ratio_icon} {n_refs}:{n_claims} "
        f"({'evidence outpaces theory ✓' if ratio_ok else 'theory outpacing evidence — run more profiles first'}) |",
        "",
        "**Rule:** Number of reference profiles should be ≥ number of active claims.",
        "See `calibra/claims/SPEC.md` for the full contribution protocol.",
        "",
        "---",
        "",
        "## Reference Profiles",
        "",
        "| Dataset | File |",
        "|---------|------|",
    ]
    for ref in references:
        lines.append(f"| {ref} | `calibra/references/{ref}.json` |")

    lines += [
        "",
        "---",
        "",
        "## Claims",
        "",
    ]

    # Group by metric
    by_metric: dict[str, list[dict]] = {}
    for claim in claims:
        m = claim.get("metric", "unknown")
        by_metric.setdefault(m, []).append(claim)

    for metric, metric_claims in sorted(by_metric.items()):
        lines.append(f"### {metric.replace('_', ' ').title()}")
        lines.append("")
        for claim in metric_claims:
            _render_claim(claim, lines)

    return "\n".join(lines) + "\n"


def _render_claim(claim: dict, lines: list[str]) -> None:
    cid = claim.get("id", "?")
    status = _STATUS_EMOJI.get(claim.get("status", ""), claim.get("status", ""))
    conf = _CONFIDENCE_BADGE.get(claim.get("confidence", ""), claim.get("confidence", ""))
    cls = claim.get("class", "any")
    assertion = claim.get("assertion", "")
    conditions = claim.get("conditions", "")
    evidence = claim.get("evidence", [])
    caution = claim.get("caution", "")
    last_updated = claim.get("last_updated", "")

    lines += [
        f"#### {cid} — {cls}",
        "",
        f"**Status:** {status}  ",
        f"**Confidence:** {conf}  ",
        f"**Class:** `{cls}`  ",
        f"**Source:** `calibra/claims/{claim.get('_source_file', '')}`  ",
        "",
        f"**Assertion:** {assertion}",
        "",
    ]

    if conditions:
        lines += [f"**Conditions:** {conditions}", ""]

    if caution:
        lines += [f"> ⚠️ **Caution:** {caution}", ""]

    if evidence:
        lines += ["**Evidence:**", ""]
        lines.append("| Dataset | Observed | Supports | Date | Notes |")
        lines.append("|---------|----------|----------|------|-------|")
        for e in evidence:
            ds = e.get("dataset", "?")
            obs = e.get("observed", "n/a")
            supports = "✅" if e.get("supports", True) else "❌"
            date = e.get("date", "")
            notes = e.get("notes", "").replace("|", "\\|")
            if isinstance(obs, float):
                obs = f"{obs:.4g}"
            lines.append(f"| `{ds}` | {obs} | {supports} | {date} | {notes} |")
        lines.append("")

    falsification = claim.get("falsification", {})
    if falsification.get("condition"):
        lines += [
            "**Falsification condition:**",
            f"> {falsification['condition']}",
            "",
        ]

    pending = falsification.get("pending_tests", [])
    if pending:
        lines += ["**Pending tests:**", ""]
        for pt in pending:
            ds = pt.get("dataset", "?")
            reason = pt.get("reason", "")
            lines.append(f"- `{ds}`: {reason}")
        lines.append("")

    if last_updated:
        lines += [f"*Last updated: {last_updated}*", ""]

    lines.append("---")
    lines.append("")


def _render_claims_yaml(claims: list[dict]) -> str:
    """Generate a human-readable YAML surface from the parsed claim list."""
    lines = [
        "# Calibra Knowledge Base — claims.yaml",
        "# Auto-generated from calibra/claims/*.json",
        "# Do not edit — edit the source JSON files and re-run:",
        "#   python scripts/generate_claims_doc.py",
        "",
        "claims:",
    ]
    for claim in claims:
        cid = claim.get("id", "?")
        lines.append(f"  - id: \"{cid}\"")
        lines.append(f"    metric: \"{claim.get('metric', '')}\"")
        lines.append(f"    class: \"{claim.get('class', 'any')}\"")
        lines.append(f"    status: \"{claim.get('status', '')}\"")
        lines.append(f"    confidence: \"{claim.get('confidence', '')}\"")
        assertion = claim.get("assertion", "").replace('"', "'")
        lines.append(f"    assertion: \"{assertion}\"")
        evidence = claim.get("evidence", [])
        lines.append(f"    evidence_count: {len(evidence)}")
        if evidence:
            lines.append("    evidence_datasets:")
            for e in evidence:
                tick = "✓" if e.get("supports", True) else "✗"
                obs = e.get("observed", "")
                lines.append(f"      - {e.get('dataset', '?')}  # {tick} {obs}")
        falsify = claim.get("falsification", {})
        if falsify.get("condition"):
            cond = falsify["condition"].replace('"', "'")
            lines.append(f"    falsification: \"{cond}\"")
        pending = falsify.get("pending_tests", [])
        if pending:
            lines.append("    pending_tests:")
            for pt in pending:
                lines.append(f"      - {pt.get('dataset', '?')}")
        if claim.get("caution"):
            lines.append("    caution: |")
            for sentence in claim["caution"].split(". "):
                s = sentence.strip()
                if s:
                    lines.append(f"      {s}.")
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--out", default="docs/claims.md",
                        help="Output path (default: docs/claims.md)")
    parser.add_argument("--check", action="store_true",
                        help="Exit 1 if references < claims (CI guard)")
    args = parser.parse_args()

    claims_dir = _REPO / "calibra" / "claims"
    refs_dir   = _REPO / "calibra" / "references"

    claims    = load_claims(claims_dir)
    references = load_references(refs_dir)

    n_claims = len(claims)
    n_refs   = len(references)

    if args.check:
        if n_refs < n_claims:
            print(
                f"❌ Claims/references ratio inverted: "
                f"{n_claims} claims, {n_refs} references.\n"
                f"   Run more dataset profiles before adding new claims.",
                file=sys.stderr,
            )
            sys.exit(1)
        print(f"✅ Ratio OK: {n_refs} references ≥ {n_claims} claims")
        sys.exit(0)

    doc = render_claims_doc(claims, references)

    out_path = _REPO / args.out
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(doc)

    # Also regenerate knowledge_base/claims.yaml (human-readable YAML surface).
    yaml_path = _REPO / "calibra" / "knowledge_base" / "claims.yaml"
    yaml_path.parent.mkdir(parents=True, exist_ok=True)
    yaml_path.write_text(_render_claims_yaml(claims))
    print(f"Written to {out_path}  +  {yaml_path}")
    print(f"  {n_claims} claims  ·  {n_refs} references  ·  ratio {'✅' if n_refs >= n_claims else '⚠️ inverted'}")


if __name__ == "__main__":
    main()
